// Generated by CodiumAI

import { Sender, Receiver } from "../azure-service-bus-admin.decorators";

describe('Sender', () => {

    // Tests that the function works correctly when called with a valid queue name
    it('should work correctly when called with a valid queue name', () => {
        // Mock the queue name
        const queue = 'validQueue';
        // Call the Sender function
        const resp = Sender(queue);
        // Verify that the Inject decorator was called with the correct argument
        expect(resp.constructor.name).toEqual("Function");
    });

});


describe('Receiver', () => {

    // Tests that the function works correctly when called with a valid queue name
    it('should work correctly when called with a valid queue name', () => {
        // Mock the receiver config
        const receiverConfig = { name: 'validQueue' };
        // Call the Receiver function
        const resp = Receiver(receiverConfig);
        // Verify that the Inject decorator was called with the correct argument
        expect(resp.constructor.name).toEqual("Function");
    });

    // Tests that the function works correctly when called with a valid queue name and subqueue
    it('should work correctly when called with a valid queue name and subqueue', () => {
        // Mock the receiver config with subqueue
        const receiverConfig = { name: 'validQueue', subqueue: true};
        // Call the Receiver function
        const resp = Receiver(receiverConfig);
        // Verify that the Inject decorator was called with the correct argument
        expect(resp.constructor.name).toEqual("Function");
    });

    // Tests that the function works correctly when called with a valid queue name and sessionId
    it('should work correctly when called with a valid queue name and sessionId', () => {
        // Mock the receiver config with sessionId
        const receiverConfig = { name: 'validQueue', sessionId: 'session123' };
        // Call the Receiver function
        const resp = Receiver(receiverConfig);
        // Verify that the Inject decorator was called with the correct argument
        expect(resp.constructor.name).toEqual("Function"); 
    });
});